<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ناس</title>
    <style>
        body {
            background-color: #6a0dad; /* لون خلفية بنفسجي */
            font-family: Arial, sans-serif;
            color: white;
            text-align: center;
            padding: 50px;
        }

        .logo {
            font-size: 3em;
            font-weight: bold;
            color: #32cd32; /* لون الشعار أخضر */
            margin-bottom: 20px;
        }

        .card {
            background: rgba(255, 255, 255, 0.1);
            border-radius: 10px;
            margin: 20px auto;
            padding: 20px;
            max-width: 300px;
            transition: transform 0.2s;
        }

        .card:hover {
            transform: scale(1.05);
        }

        .card a {
            text-decoration: none;
            color: #fff;
            font-size: 1.2em;
        }

        .card img {
            width: 100%;
            border-radius: 10px;
        }

        .card-title {
            margin: 10px 0;
            font-size: 1.5em;
        }

    </style>
</head>
<body>
    <div class="logo">ناس</div>

    <div class="card">
        <a href="https://www.youtube.com" target="_blank">
            <img src="https://via.placeholder.com/300x150?text=YouTube" alt="YouTube">
            <div class="card-title">يوتيوب</div>
        </a>
    </div>

    <div class="card">
        <a href="https://www.instagram.com" target="_blank">
            <img src="https://via.placeholder.com/300x150?text=Instagram" alt="Instagram">
            <div class="card-title">إنستغرام</div>
        </a>
    </div>

    <div class="card">
        <a href="https://www.facebook.com" target="_blank">
            <img src="https://via.placeholder.com/300x150?text=Facebook" alt="Facebook">
            <div class="card-title">فيسبوك</div>
        </a>
    </div>

    <div class="card">
        <a href="https://www.twitter.com" target="_blank">
            <img src="https://via.placeholder.com/300x150?text=Twitter" alt="Twitter">
            <div class="card-title">تويتر</div>
        </a>
    </div>
</body>
</html>
